---  
- name: "Download package from url"
  ansible.builtin.get_url:
    url: '{{ jdk11_install_url }}'
    dest: "{{ jdk11_temp_path }}"
    timeout: '60'
    mode: '0777'
  register: dl


- name: "Create java directory"
  ansible.builtin.file:
    path: "{{ jdk11_install_dir }}"
    state: directory
    mode: '0755'
    
- name: "Unzip package"
  ansible.builtin.command:
    tar -xvf "{{ jdk11_temp_path }}/{{ jdk11_bin_name }}" -C "{{ jdk11_install_dir }}"


- name: "Put 0755 rights"
  ansible.builtin.file:
    path: "{{ jdk11_install_dir }}"
    mode: '0755'
    recurse: yes
    state: directory
