---
- name: "Retrieve install package from path"
  ansible.builtin.copy:
    src: "{{ jdk11_install_path }}{% if jdk11_install_path | length > 0 %}/{% endif %}{{ jdk11_bin_name }}"
    dest: "{{ jdk11_temp_path }}"
    mode: '0755'
    force: false
  register: dl
  when:
    - jdk11_install_method == "file"
    - jdk11_install_path is defined
    - jdk11_install_path | length > 0
    
- name: "Download package from url"
  ansible.builtin.get_url:
    url: '{{ jdk11_install_url }}'
    dest: "{{ jdk11_temp_path }}"
    timeout: '60'
    mode: '0777'
  register: dl
  when:
    - jdk11_install_method == "url"
    - jdk11_install_url is defined
    - jdk11_install_url | length > 0

- name: "Create java directory"
  ansible.builtin.file:
    path: "{{ jdk11_install_dir }}"
    state: directory
    mode: '0755'
    
- name: "Unzip package"
  ansible.builtin.command:
    tar -xvf "{{ jdk11_temp_path }}/{{ jdk11_bin_name }}" -C "{{ jdk11_install_dir }}"


- name: "Put 0755 rights"
  ansible.builtin.file:
    path: "{{ jdk11_install_dir }}"
    mode: '0755'
    recurse: yes
    state: directory
